#!/bin/sh

#bcn, Bluetooth Connect

select=$(bluetoothctl devices | awk {'print $3'} | dmenu -l 10 -fn Monospace-15)
MAC=$(bluetoothctl devices | grep $select | awk {'print $2'})

connect=$(bluetoothctl info $MAC | grep Connected: | awk '{print $2}')
if [[ $connect = no ]]; then 
	notify-send "Attempting to connect to $select"
	bluetoothctl connect $MAC || notify-send "Failed to Connect"
else
	notify-send "Attempting to disconnect $select"
	bluetoothctl disconnect $MAC 
fi
